CREATE TABLE IF NOT EXISTS build_runs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    provider text NOT NULL CHECK (provider IN ('github_actions', 'cloud_build')),
    connector_id uuid REFERENCES connector_accounts(id) ON DELETE SET NULL,
    application_id uuid REFERENCES applications(id) ON DELETE SET NULL,
    repository text NOT NULL,
    branch text NOT NULL,
    workflow_id text NOT NULL,
    status text NOT NULL DEFAULT 'dispatched' CHECK (status IN ('dispatched', 'running', 'succeeded', 'failed', 'cancelled')),
    commit_sha text,
    image_ref text,
    image_digest text,
    external_url text,
    error_message text,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(repository) <> '' AND repository ~ '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'),
    CHECK (btrim(branch) <> ''),
    CHECK (btrim(branch) !~ '^-'),
    CHECK (btrim(branch) !~ '(^/|/$|//)'),
    CHECK (btrim(branch) !~ '(\.\.|\.lock$|\.$)'),
    CHECK (btrim(branch) ~ '^[A-Za-z0-9._/-]+$'),
    CHECK (btrim(workflow_id) <> '' AND workflow_id !~ '[/\\[:space:][:cntrl:]]'),
    CHECK (commit_sha IS NULL OR commit_sha ~ '^[0-9A-Fa-f]{7,40}$'),
    CHECK (image_ref IS NULL OR (btrim(image_ref) <> '' AND length(image_ref) <= 512 AND image_ref !~ '[[:space:][:cntrl:]]')),
    CHECK (image_digest IS NULL OR image_digest ~ '^sha256:[0-9a-f]{64}$'),
    CHECK (external_url IS NULL OR (btrim(external_url) <> '' AND external_url ~ '^https://' AND external_url !~ '[[:cntrl:]]' AND external_url !~ '^https?://[^/@]+@')),
    CHECK (error_message IS NULL OR (btrim(error_message) <> '' AND length(error_message) <= 512 AND error_message !~ '[[:cntrl:]]')),
    CHECK ((status IN ('succeeded', 'failed', 'cancelled') AND completed_at IS NOT NULL) OR status NOT IN ('succeeded', 'failed', 'cancelled')),
    CHECK ((status = 'succeeded' AND image_ref IS NOT NULL) OR status <> 'succeeded')
);
