// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateDeploymentSlot = `-- name: ActivateDeploymentSlot :many
UPDATE application_deployment_slots
SET status = CASE WHEN color = $1::text THEN 'active' ELSE 'standby' END,
    promoted_at = CASE WHEN color = $1::text THEN now() ELSE promoted_at END,
    updated_at = now()
WHERE application_id = $2::uuid
  AND server_id = $3::uuid
  AND status IN ('active', 'standby')
RETURNING id, application_id, server_id, color, deployment_id, image_ref, image_digest, status, promoted_at, created_at, updated_at
`

type ActivateDeploymentSlotParams struct {
	Color         string      `json:"color"`
	ApplicationID pgtype.UUID `json:"application_id"`
	ServerID      pgtype.UUID `json:"server_id"`
}

func (q *Queries) ActivateDeploymentSlot(ctx context.Context, arg ActivateDeploymentSlotParams) ([]ApplicationDeploymentSlot, error) {
	rows, err := q.db.Query(ctx, activateDeploymentSlot, arg.Color, arg.ApplicationID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationDeploymentSlot{}
	for rows.Next() {
		var i ApplicationDeploymentSlot
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ServerID,
			&i.Color,
			&i.DeploymentID,
			&i.ImageRef,
			&i.ImageDigest,
			&i.Status,
			&i.PromotedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (actor, action, target_type, target_id, target_name, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor, action, target_type, target_id, target_name, metadata, created_at
`

type AppendAuditEventParams struct {
	Actor      string `json:"actor"`
	Action     string `json:"action"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	TargetName string `json:"target_name"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.TargetName,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const appendDeploymentLog = `-- name: AppendDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, stream, message)
VALUES ($1, $2, $3)
RETURNING id, deployment_id, stream, message, created_at
`

type AppendDeploymentLogParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	Stream       string      `json:"stream"`
	Message      string      `json:"message"`
}

func (q *Queries) AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRow(ctx, appendDeploymentLog, arg.DeploymentID, arg.Stream, arg.Message)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Stream,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const cancelQueuedDeployment = `-- name: CancelQueuedDeployment :one
UPDATE deployments
SET status = 'cancelled',
    finished_at = now()
WHERE id = $1
  AND status = 'queued'
RETURNING id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
`

func (q *Queries) CancelQueuedDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, cancelQueuedDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Trigger,
		&i.Strategy,
		&i.Status,
		&i.CommitSha,
		&i.Actor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.ImageRef,
		&i.ImageDigest,
	)
	return i, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (environment_id, server_id, name, repository_url, branch, compose_path, remote_directory, domain, health_check_url, doppler_project, doppler_config, github_auto_deploy)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, environment_id, server_id, name, repository_url, branch, compose_path, remote_directory, domain, health_check_url, doppler_project, doppler_config, status, current_version, target_version, created_at, updated_at, github_auto_deploy
`

type CreateApplicationParams struct {
	EnvironmentID    pgtype.UUID `json:"environment_id"`
	ServerID         pgtype.UUID `json:"server_id"`
	Name             string      `json:"name"`
	RepositoryUrl    pgtype.Text `json:"repository_url"`
	Branch           string      `json:"branch"`
	ComposePath      string      `json:"compose_path"`
	RemoteDirectory  string      `json:"remote_directory"`
	Domain           pgtype.Text `json:"domain"`
	HealthCheckUrl   pgtype.Text `json:"health_check_url"`
	DopplerProject   pgtype.Text `json:"doppler_project"`
	DopplerConfig    pgtype.Text `json:"doppler_config"`
	GithubAutoDeploy bool        `json:"github_auto_deploy"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.EnvironmentID,
		arg.ServerID,
		arg.Name,
		arg.RepositoryUrl,
		arg.Branch,
		arg.ComposePath,
		arg.RemoteDirectory,
		arg.Domain,
		arg.HealthCheckUrl,
		arg.DopplerProject,
		arg.DopplerConfig,
		arg.GithubAutoDeploy,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ServerID,
		&i.Name,
		&i.RepositoryUrl,
		&i.Branch,
		&i.ComposePath,
		&i.RemoteDirectory,
		&i.Domain,
		&i.HealthCheckUrl,
		&i.DopplerProject,
		&i.DopplerConfig,
		&i.Status,
		&i.CurrentVersion,
		&i.TargetVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAutoDeploy,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (application_id, server_id, trigger, strategy, status, commit_sha, image_ref, image_digest, actor)
SELECT applications.id,
       applications.server_id,
       $1::text,
       $2::text,
       'queued',
       $3::text,
       $4::text,
       $5::text,
       $6::text
FROM applications
WHERE applications.id = $7::uuid
RETURNING id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
`

type CreateDeploymentParams struct {
	Trigger       string      `json:"trigger"`
	Strategy      string      `json:"strategy"`
	CommitSha     pgtype.Text `json:"commit_sha"`
	ImageRef      pgtype.Text `json:"image_ref"`
	ImageDigest   pgtype.Text `json:"image_digest"`
	Actor         pgtype.Text `json:"actor"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.Trigger,
		arg.Strategy,
		arg.CommitSha,
		arg.ImageRef,
		arg.ImageDigest,
		arg.Actor,
		arg.ApplicationID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Trigger,
		&i.Strategy,
		&i.Status,
		&i.CommitSha,
		&i.Actor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.ImageRef,
		&i.ImageDigest,
	)
	return i, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, slug, kind, is_ephemeral, pull_request_number, branch, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, slug, kind, is_ephemeral, pull_request_number, branch, expires_at, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Kind              string             `json:"kind"`
	IsEphemeral       bool               `json:"is_ephemeral"`
	PullRequestNumber pgtype.Int4        `json:"pull_request_number"`
	Branch            pgtype.Text        `json:"branch"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Kind,
		arg.IsEphemeral,
		arg.PullRequestNumber,
		arg.Branch,
		arg.ExpiresAt,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.IsEphemeral,
		&i.PullRequestNumber,
		&i.Branch,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectWithDefaultEnvironments = `-- name: CreateProjectWithDefaultEnvironments :one
WITH created_project AS (
    INSERT INTO projects (name, slug, description)
    VALUES ($1, $2, $3)
    RETURNING id, name, slug, description, created_at, updated_at, default_registry_id
),
created_environments AS (
    INSERT INTO environments (project_id, name, slug, kind, is_ephemeral)
    SELECT id, 'Production', 'production', 'production', false FROM created_project
    UNION ALL
    SELECT id, 'Development', 'development', 'development', false FROM created_project
    RETURNING id
)
SELECT id, name, slug, description, created_at, updated_at, default_registry_id
FROM created_project
`

type CreateProjectWithDefaultEnvironmentsParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

type CreateProjectWithDefaultEnvironmentsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DefaultRegistryID pgtype.UUID        `json:"default_registry_id"`
}

func (q *Queries) CreateProjectWithDefaultEnvironments(ctx context.Context, arg CreateProjectWithDefaultEnvironmentsParams) (CreateProjectWithDefaultEnvironmentsRow, error) {
	row := q.db.QueryRow(ctx, createProjectWithDefaultEnvironments, arg.Name, arg.Slug, arg.Description)
	var i CreateProjectWithDefaultEnvironmentsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultRegistryID,
	)
	return i, err
}

const createProxyRoute = `-- name: CreateProxyRoute :one
INSERT INTO proxy_routes (server_id, application_id, domain, upstream_url, tls_enabled, blue_upstream_url, green_upstream_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (server_id, domain) DO UPDATE
SET application_id = excluded.application_id,
    upstream_url = excluded.upstream_url,
    tls_enabled = excluded.tls_enabled,
    blue_upstream_url = excluded.blue_upstream_url,
    green_upstream_url = excluded.green_upstream_url,
    status = 'pending',
    updated_at = now()
RETURNING id, server_id, application_id, domain, upstream_url, tls_enabled, status, last_applied_at, created_at, updated_at, blue_upstream_url, green_upstream_url
`

type CreateProxyRouteParams struct {
	ServerID         pgtype.UUID `json:"server_id"`
	ApplicationID    pgtype.UUID `json:"application_id"`
	Domain           string      `json:"domain"`
	UpstreamUrl      string      `json:"upstream_url"`
	TlsEnabled       bool        `json:"tls_enabled"`
	BlueUpstreamUrl  pgtype.Text `json:"blue_upstream_url"`
	GreenUpstreamUrl pgtype.Text `json:"green_upstream_url"`
}

func (q *Queries) CreateProxyRoute(ctx context.Context, arg CreateProxyRouteParams) (ProxyRoute, error) {
	row := q.db.QueryRow(ctx, createProxyRoute,
		arg.ServerID,
		arg.ApplicationID,
		arg.Domain,
		arg.UpstreamUrl,
		arg.TlsEnabled,
		arg.BlueUpstreamUrl,
		arg.GreenUpstreamUrl,
	)
	var i ProxyRoute
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ApplicationID,
		&i.Domain,
		&i.UpstreamUrl,
		&i.TlsEnabled,
		&i.Status,
		&i.LastAppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlueUpstreamUrl,
		&i.GreenUpstreamUrl,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type, status, cpu_usage, memory_usage, disk_usage, last_checked_at, created_at, updated_at
`

type CreateServerParams struct {
	Name           string      `json:"name"`
	Hostname       string      `json:"hostname"`
	SshUser        string      `json:"ssh_user"`
	SshPort        int32       `json:"ssh_port"`
	SshKeyPath     pgtype.Text `json:"ssh_key_path"`
	ConnectionMode string      `json:"connection_mode"`
	ProxyType      string      `json:"proxy_type"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.Hostname,
		arg.SshUser,
		arg.SshPort,
		arg.SshKeyPath,
		arg.ConnectionMode,
		arg.ProxyType,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.SshUser,
		&i.SshPort,
		&i.SshKeyPath,
		&i.ConnectionMode,
		&i.ProxyType,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.DiskUsage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServerWithSSHInventory = `-- name: CreateServerWithSSHInventory :one
WITH created_server AS (
    INSERT INTO servers (name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type, status, cpu_usage, memory_usage, disk_usage, last_checked_at, created_at, updated_at
),
ssh_credential AS (
    INSERT INTO credentials (name, provider, external_ref, credential_type, status, last_seen_at)
    SELECT created_server.name || ' SSH key', 'ssh', created_server.ssh_key_path, 'ssh_key', 'active', now()
    FROM created_server
    WHERE created_server.ssh_key_path IS NOT NULL
    ON CONFLICT (provider, external_ref) DO UPDATE
    SET name = excluded.name,
        credential_type = excluded.credential_type,
        status = excluded.status,
        last_seen_at = now(),
        updated_at = now()
    RETURNING id
),
ssh_permission AS (
    INSERT INTO credential_permissions (credential_id, resource_type, resource_name, permission, source)
    SELECT ssh_credential.id, 'server', created_server.name, 'ssh:connect', 'server registration'
    FROM ssh_credential
    CROSS JOIN created_server
    ON CONFLICT (credential_id, resource_type, resource_name, permission) DO UPDATE
    SET source = excluded.source
    RETURNING id
),
ssh_usage AS (
    INSERT INTO credential_usages (credential_id, used_by_type, used_by_name, usage_context)
    SELECT ssh_credential.id, 'server', created_server.name, 'remote access for deployments and health checks'
    FROM ssh_credential
    CROSS JOIN created_server
    ON CONFLICT (credential_id, used_by_type, used_by_name, usage_context) DO UPDATE
    SET usage_context = excluded.usage_context
    RETURNING id
)
SELECT id, name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type, status, cpu_usage, memory_usage, disk_usage, last_checked_at, created_at, updated_at
FROM created_server
`

type CreateServerWithSSHInventoryParams struct {
	Name           string      `json:"name"`
	Hostname       string      `json:"hostname"`
	SshUser        string      `json:"ssh_user"`
	SshPort        int32       `json:"ssh_port"`
	SshKeyPath     pgtype.Text `json:"ssh_key_path"`
	ConnectionMode string      `json:"connection_mode"`
	ProxyType      string      `json:"proxy_type"`
}

type CreateServerWithSSHInventoryRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Hostname       string             `json:"hostname"`
	SshUser        string             `json:"ssh_user"`
	SshPort        int32              `json:"ssh_port"`
	SshKeyPath     pgtype.Text        `json:"ssh_key_path"`
	ConnectionMode string             `json:"connection_mode"`
	ProxyType      string             `json:"proxy_type"`
	Status         string             `json:"status"`
	CpuUsage       pgtype.Numeric     `json:"cpu_usage"`
	MemoryUsage    pgtype.Numeric     `json:"memory_usage"`
	DiskUsage      pgtype.Numeric     `json:"disk_usage"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateServerWithSSHInventory(ctx context.Context, arg CreateServerWithSSHInventoryParams) (CreateServerWithSSHInventoryRow, error) {
	row := q.db.QueryRow(ctx, createServerWithSSHInventory,
		arg.Name,
		arg.Hostname,
		arg.SshUser,
		arg.SshPort,
		arg.SshKeyPath,
		arg.ConnectionMode,
		arg.ProxyType,
	)
	var i CreateServerWithSSHInventoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.SshUser,
		&i.SshPort,
		&i.SshKeyPath,
		&i.ConnectionMode,
		&i.ProxyType,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.DiskUsage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const deleteCredentialPermissions = `-- name: DeleteCredentialPermissions :exec
DELETE FROM credential_permissions
WHERE credential_id = $1
`

func (q *Queries) DeleteCredentialPermissions(ctx context.Context, credentialID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredentialPermissions, credentialID)
	return err
}

const deleteCredentialUsages = `-- name: DeleteCredentialUsages :exec
DELETE FROM credential_usages
WHERE credential_id = $1
`

func (q *Queries) DeleteCredentialUsages(ctx context.Context, credentialID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredentialUsages, credentialID)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments
WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteProxyRoute = `-- name: DeleteProxyRoute :exec
DELETE FROM proxy_routes
WHERE id = $1
`

func (q *Queries) DeleteProxyRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProxyRoute, id)
	return err
}

const failRunningDeploymentsForRecovery = `-- name: FailRunningDeploymentsForRecovery :many
WITH failed_deployments AS (
    UPDATE deployments
    SET status = 'failed',
        finished_at = now()
    WHERE status = 'running'
    RETURNING id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
),
failed_applications AS (
    UPDATE applications
    SET status = 'failed',
        updated_at = now()
    WHERE id IN (SELECT application_id FROM failed_deployments)
    RETURNING id
)
SELECT failed_deployments.id,
       failed_deployments.application_id,
       failed_deployments.server_id,
       failed_deployments.trigger,
       failed_deployments.strategy,
       failed_deployments.status,
       failed_deployments.commit_sha,
       failed_deployments.image_ref,
       failed_deployments.image_digest,
       failed_deployments.actor,
       failed_deployments.started_at,
       failed_deployments.finished_at,
       failed_deployments.created_at
FROM failed_deployments
`

type FailRunningDeploymentsForRecoveryRow struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	ServerID      pgtype.UUID        `json:"server_id"`
	Trigger       string             `json:"trigger"`
	Strategy      string             `json:"strategy"`
	Status        string             `json:"status"`
	CommitSha     pgtype.Text        `json:"commit_sha"`
	ImageRef      pgtype.Text        `json:"image_ref"`
	ImageDigest   pgtype.Text        `json:"image_digest"`
	Actor         pgtype.Text        `json:"actor"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FailRunningDeploymentsForRecovery(ctx context.Context) ([]FailRunningDeploymentsForRecoveryRow, error) {
	rows, err := q.db.Query(ctx, failRunningDeploymentsForRecovery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailRunningDeploymentsForRecoveryRow{}
	for rows.Next() {
		var i FailRunningDeploymentsForRecoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ServerID,
			&i.Trigger,
			&i.Strategy,
			&i.Status,
			&i.CommitSha,
			&i.ImageRef,
			&i.ImageDigest,
			&i.Actor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveDeploymentSlot = `-- name: GetActiveDeploymentSlot :one
SELECT id, application_id, server_id, color, deployment_id, image_ref, image_digest, status, promoted_at, created_at, updated_at
FROM application_deployment_slots
WHERE application_id = $1
  AND server_id = $2
  AND status = 'active'
ORDER BY updated_at DESC
LIMIT 1
`

type GetActiveDeploymentSlotParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	ServerID      pgtype.UUID `json:"server_id"`
}

func (q *Queries) GetActiveDeploymentSlot(ctx context.Context, arg GetActiveDeploymentSlotParams) (ApplicationDeploymentSlot, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentSlot, arg.ApplicationID, arg.ServerID)
	var i ApplicationDeploymentSlot
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Color,
		&i.DeploymentID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.Status,
		&i.PromotedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, environment_id, server_id, name, repository_url, branch, compose_path, remote_directory, domain, health_check_url, doppler_project, doppler_config, status, current_version, target_version, created_at, updated_at, github_auto_deploy
FROM applications
WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ServerID,
		&i.Name,
		&i.RepositoryUrl,
		&i.Branch,
		&i.ComposePath,
		&i.RemoteDirectory,
		&i.Domain,
		&i.HealthCheckUrl,
		&i.DopplerProject,
		&i.DopplerConfig,
		&i.Status,
		&i.CurrentVersion,
		&i.TargetVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAutoDeploy,
	)
	return i, err
}

const getConnectorAccount = `-- name: GetConnectorAccount :one
SELECT id, provider, name, enabled, config, last_sync_status, last_sync_message, last_synced_at, created_at, updated_at
FROM connector_accounts
WHERE id = $1
`

func (q *Queries) GetConnectorAccount(ctx context.Context, id pgtype.UUID) (ConnectorAccount, error) {
	row := q.db.QueryRow(ctx, getConnectorAccount, id)
	var i ConnectorAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.LastSyncStatus,
		&i.LastSyncMessage,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContainerRegistry = `-- name: GetContainerRegistry :one
SELECT id, name, provider, registry_host, namespace, repository, default_image, enabled, created_at, updated_at
FROM container_registries
WHERE id = $1
`

func (q *Queries) GetContainerRegistry(ctx context.Context, id pgtype.UUID) (ContainerRegistry, error) {
	row := q.db.QueryRow(ctx, getContainerRegistry, id)
	var i ContainerRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RegistryHost,
		&i.Namespace,
		&i.Repository,
		&i.DefaultImage,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, name, provider, external_ref, credential_type, status, last_seen_at, created_at, updated_at
FROM credentials
WHERE id = $1
`

func (q *Queries) GetCredential(ctx context.Context, id pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ExternalRef,
		&i.CredentialType,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialWithCounts = `-- name: GetCredentialWithCounts :one
SELECT c.id, c.name, c.provider, c.external_ref, c.credential_type, c.status, c.last_seen_at, c.created_at, c.updated_at,
       COALESCE(count(DISTINCT p.id), 0)::int AS permission_count,
       COALESCE(count(DISTINCT u.id), 0)::int AS usage_count
FROM credentials c
LEFT JOIN credential_permissions p ON p.credential_id = c.id
LEFT JOIN credential_usages u ON u.credential_id = c.id
WHERE c.id = $1
GROUP BY c.id
`

type GetCredentialWithCountsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Provider        string             `json:"provider"`
	ExternalRef     string             `json:"external_ref"`
	CredentialType  string             `json:"credential_type"`
	Status          string             `json:"status"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PermissionCount int32              `json:"permission_count"`
	UsageCount      int32              `json:"usage_count"`
}

func (q *Queries) GetCredentialWithCounts(ctx context.Context, id pgtype.UUID) (GetCredentialWithCountsRow, error) {
	row := q.db.QueryRow(ctx, getCredentialWithCounts, id)
	var i GetCredentialWithCountsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ExternalRef,
		&i.CredentialType,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PermissionCount,
		&i.UsageCount,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Trigger,
		&i.Strategy,
		&i.Status,
		&i.CommitSha,
		&i.Actor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.ImageRef,
		&i.ImageDigest,
	)
	return i, err
}

const getDeploymentTarget = `-- name: GetDeploymentTarget :one
SELECT d.id AS deployment_id,
       d.strategy,
       d.commit_sha,
       d.image_ref,
       d.image_digest,
       a.id AS application_id,
       a.name AS application_name,
       a.repository_url,
       a.branch,
       a.compose_path,
       a.remote_directory,
       a.domain,
       a.health_check_url,
       a.doppler_project,
       a.doppler_config,
       s.id AS server_id,
       s.name AS server_name,
       s.hostname,
       s.ssh_user,
       s.ssh_port,
       s.ssh_key_path,
       s.connection_mode,
       s.proxy_type
FROM deployments d
JOIN applications a ON a.id = d.application_id
JOIN servers s ON s.id = d.server_id
WHERE d.id = $1
`

type GetDeploymentTargetRow struct {
	DeploymentID    pgtype.UUID `json:"deployment_id"`
	Strategy        string      `json:"strategy"`
	CommitSha       pgtype.Text `json:"commit_sha"`
	ImageRef        pgtype.Text `json:"image_ref"`
	ImageDigest     pgtype.Text `json:"image_digest"`
	ApplicationID   pgtype.UUID `json:"application_id"`
	ApplicationName string      `json:"application_name"`
	RepositoryUrl   pgtype.Text `json:"repository_url"`
	Branch          string      `json:"branch"`
	ComposePath     string      `json:"compose_path"`
	RemoteDirectory string      `json:"remote_directory"`
	Domain          pgtype.Text `json:"domain"`
	HealthCheckUrl  pgtype.Text `json:"health_check_url"`
	DopplerProject  pgtype.Text `json:"doppler_project"`
	DopplerConfig   pgtype.Text `json:"doppler_config"`
	ServerID        pgtype.UUID `json:"server_id"`
	ServerName      string      `json:"server_name"`
	Hostname        string      `json:"hostname"`
	SshUser         string      `json:"ssh_user"`
	SshPort         int32       `json:"ssh_port"`
	SshKeyPath      pgtype.Text `json:"ssh_key_path"`
	ConnectionMode  string      `json:"connection_mode"`
	ProxyType       string      `json:"proxy_type"`
}

func (q *Queries) GetDeploymentTarget(ctx context.Context, id pgtype.UUID) (GetDeploymentTargetRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentTarget, id)
	var i GetDeploymentTargetRow
	err := row.Scan(
		&i.DeploymentID,
		&i.Strategy,
		&i.CommitSha,
		&i.ImageRef,
		&i.ImageDigest,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.RepositoryUrl,
		&i.Branch,
		&i.ComposePath,
		&i.RemoteDirectory,
		&i.Domain,
		&i.HealthCheckUrl,
		&i.DopplerProject,
		&i.DopplerConfig,
		&i.ServerID,
		&i.ServerName,
		&i.Hostname,
		&i.SshUser,
		&i.SshPort,
		&i.SshKeyPath,
		&i.ConnectionMode,
		&i.ProxyType,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, name, slug, kind, is_ephemeral, pull_request_number, branch, expires_at, created_at, updated_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.IsEphemeral,
		&i.PullRequestNumber,
		&i.Branch,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, name, short_name, meta_description, logo_url, favicon_url, primary_color, docs_url, created_at, updated_at
FROM instance_settings
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.MetaDescription,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.DocsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, slug, description, created_at, updated_at, default_registry_id
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultRegistryID,
	)
	return i, err
}

const getProxyRouteTarget = `-- name: GetProxyRouteTarget :one
SELECT pr.id,
       pr.server_id,
       pr.application_id,
       pr.domain,
       pr.upstream_url,
       pr.tls_enabled,
       pr.status,
       pr.blue_upstream_url,
       pr.green_upstream_url,
       s.name AS server_name,
       s.hostname,
       s.ssh_user,
       s.ssh_port,
       s.ssh_key_path,
       s.proxy_type
FROM proxy_routes pr
JOIN servers s ON s.id = pr.server_id
WHERE pr.id = $1
`

type GetProxyRouteTargetRow struct {
	ID               pgtype.UUID `json:"id"`
	ServerID         pgtype.UUID `json:"server_id"`
	ApplicationID    pgtype.UUID `json:"application_id"`
	Domain           string      `json:"domain"`
	UpstreamUrl      string      `json:"upstream_url"`
	TlsEnabled       bool        `json:"tls_enabled"`
	Status           string      `json:"status"`
	BlueUpstreamUrl  pgtype.Text `json:"blue_upstream_url"`
	GreenUpstreamUrl pgtype.Text `json:"green_upstream_url"`
	ServerName       string      `json:"server_name"`
	Hostname         string      `json:"hostname"`
	SshUser          string      `json:"ssh_user"`
	SshPort          int32       `json:"ssh_port"`
	SshKeyPath       pgtype.Text `json:"ssh_key_path"`
	ProxyType        string      `json:"proxy_type"`
}

func (q *Queries) GetProxyRouteTarget(ctx context.Context, id pgtype.UUID) (GetProxyRouteTargetRow, error) {
	row := q.db.QueryRow(ctx, getProxyRouteTarget, id)
	var i GetProxyRouteTargetRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ApplicationID,
		&i.Domain,
		&i.UpstreamUrl,
		&i.TlsEnabled,
		&i.Status,
		&i.BlueUpstreamUrl,
		&i.GreenUpstreamUrl,
		&i.ServerName,
		&i.Hostname,
		&i.SshUser,
		&i.SshPort,
		&i.SshKeyPath,
		&i.ProxyType,
	)
	return i, err
}

const getServer = `-- name: GetServer :one
SELECT id, name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type, status, cpu_usage, memory_usage, disk_usage, last_checked_at, created_at, updated_at
FROM servers
WHERE id = $1
`

func (q *Queries) GetServer(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.SshUser,
		&i.SshPort,
		&i.SshKeyPath,
		&i.ConnectionMode,
		&i.ProxyType,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.DiskUsage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStandbyDeploymentSlot = `-- name: GetStandbyDeploymentSlot :one
SELECT id, application_id, server_id, color, deployment_id, image_ref, image_digest, status, promoted_at, created_at, updated_at
FROM application_deployment_slots
WHERE application_id = $1
  AND server_id = $2
  AND status = 'standby'
ORDER BY updated_at DESC
LIMIT 1
`

type GetStandbyDeploymentSlotParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	ServerID      pgtype.UUID `json:"server_id"`
}

func (q *Queries) GetStandbyDeploymentSlot(ctx context.Context, arg GetStandbyDeploymentSlotParams) (ApplicationDeploymentSlot, error) {
	row := q.db.QueryRow(ctx, getStandbyDeploymentSlot, arg.ApplicationID, arg.ServerID)
	var i ApplicationDeploymentSlot
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Color,
		&i.DeploymentID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.Status,
		&i.PromotedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT a.id, a.environment_id, a.server_id, a.name, a.repository_url, a.branch, a.compose_path, a.remote_directory, a.domain, a.health_check_url, a.doppler_project, a.doppler_config, a.status, a.current_version, a.target_version, a.created_at, a.updated_at, a.github_auto_deploy,
       s.name AS server_name,
       e.name AS environment_name,
       e.slug AS environment_slug,
       e.kind AS environment_kind,
       e.is_ephemeral AS environment_is_ephemeral,
       p.id AS project_id,
       p.name AS project_name,
       p.slug AS project_slug,
       p.default_registry_id,
       cr.name AS default_registry_name
FROM applications a
JOIN servers s ON s.id = a.server_id
JOIN environments e ON e.id = a.environment_id
JOIN projects p ON p.id = e.project_id
LEFT JOIN container_registries cr ON cr.id = p.default_registry_id
ORDER BY a.name
`

type ListApplicationsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	ServerID               pgtype.UUID        `json:"server_id"`
	Name                   string             `json:"name"`
	RepositoryUrl          pgtype.Text        `json:"repository_url"`
	Branch                 string             `json:"branch"`
	ComposePath            string             `json:"compose_path"`
	RemoteDirectory        string             `json:"remote_directory"`
	Domain                 pgtype.Text        `json:"domain"`
	HealthCheckUrl         pgtype.Text        `json:"health_check_url"`
	DopplerProject         pgtype.Text        `json:"doppler_project"`
	DopplerConfig          pgtype.Text        `json:"doppler_config"`
	Status                 string             `json:"status"`
	CurrentVersion         pgtype.Text        `json:"current_version"`
	TargetVersion          pgtype.Text        `json:"target_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	GithubAutoDeploy       bool               `json:"github_auto_deploy"`
	ServerName             string             `json:"server_name"`
	EnvironmentName        string             `json:"environment_name"`
	EnvironmentSlug        string             `json:"environment_slug"`
	EnvironmentKind        string             `json:"environment_kind"`
	EnvironmentIsEphemeral bool               `json:"environment_is_ephemeral"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	ProjectName            string             `json:"project_name"`
	ProjectSlug            string             `json:"project_slug"`
	DefaultRegistryID      pgtype.UUID        `json:"default_registry_id"`
	DefaultRegistryName    pgtype.Text        `json:"default_registry_name"`
}

func (q *Queries) ListApplications(ctx context.Context) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsRow{}
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ServerID,
			&i.Name,
			&i.RepositoryUrl,
			&i.Branch,
			&i.ComposePath,
			&i.RemoteDirectory,
			&i.Domain,
			&i.HealthCheckUrl,
			&i.DopplerProject,
			&i.DopplerConfig,
			&i.Status,
			&i.CurrentVersion,
			&i.TargetVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GithubAutoDeploy,
			&i.ServerName,
			&i.EnvironmentName,
			&i.EnvironmentSlug,
			&i.EnvironmentKind,
			&i.EnvironmentIsEphemeral,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.DefaultRegistryID,
			&i.DefaultRegistryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsForGitHubPush = `-- name: ListApplicationsForGitHubPush :many
SELECT id, server_id, name, repository_url, branch
FROM applications
WHERE branch = $1
  AND repository_url = ANY($2::text[])
  AND github_auto_deploy = true
ORDER BY name
`

type ListApplicationsForGitHubPushParams struct {
	Branch         string   `json:"branch"`
	RepositoryUrls []string `json:"repository_urls"`
}

type ListApplicationsForGitHubPushRow struct {
	ID            pgtype.UUID `json:"id"`
	ServerID      pgtype.UUID `json:"server_id"`
	Name          string      `json:"name"`
	RepositoryUrl pgtype.Text `json:"repository_url"`
	Branch        string      `json:"branch"`
}

func (q *Queries) ListApplicationsForGitHubPush(ctx context.Context, arg ListApplicationsForGitHubPushParams) ([]ListApplicationsForGitHubPushRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsForGitHubPush, arg.Branch, arg.RepositoryUrls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsForGitHubPushRow{}
	for rows.Next() {
		var i ListApplicationsForGitHubPushRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.RepositoryUrl,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor, action, target_type, target_id, target_name, metadata, created_at
FROM audit_events
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorAccounts = `-- name: ListConnectorAccounts :many
SELECT id, provider, name, enabled, config, last_sync_status, last_sync_message, last_synced_at, created_at, updated_at
FROM connector_accounts
ORDER BY provider, name
`

func (q *Queries) ListConnectorAccounts(ctx context.Context) ([]ConnectorAccount, error) {
	rows, err := q.db.Query(ctx, listConnectorAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorAccount{}
	for rows.Next() {
		var i ConnectorAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.LastSyncStatus,
			&i.LastSyncMessage,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainerRegistries = `-- name: ListContainerRegistries :many
SELECT id, name, provider, registry_host, namespace, repository, default_image, enabled, created_at, updated_at
FROM container_registries
ORDER BY enabled DESC, name
`

func (q *Queries) ListContainerRegistries(ctx context.Context) ([]ContainerRegistry, error) {
	rows, err := q.db.Query(ctx, listContainerRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContainerRegistry{}
	for rows.Next() {
		var i ContainerRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.RegistryHost,
			&i.Namespace,
			&i.Repository,
			&i.DefaultImage,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialPermissions = `-- name: ListCredentialPermissions :many
SELECT id, credential_id, resource_type, resource_name, permission, source, created_at
FROM credential_permissions
WHERE credential_id = $1
ORDER BY resource_type, resource_name, permission
`

func (q *Queries) ListCredentialPermissions(ctx context.Context, credentialID pgtype.UUID) ([]CredentialPermission, error) {
	rows, err := q.db.Query(ctx, listCredentialPermissions, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CredentialPermission{}
	for rows.Next() {
		var i CredentialPermission
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.ResourceType,
			&i.ResourceName,
			&i.Permission,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialUsages = `-- name: ListCredentialUsages :many
SELECT id, credential_id, used_by_type, used_by_name, usage_context, created_at
FROM credential_usages
WHERE credential_id = $1
ORDER BY used_by_type, used_by_name
`

func (q *Queries) ListCredentialUsages(ctx context.Context, credentialID pgtype.UUID) ([]CredentialUsage, error) {
	rows, err := q.db.Query(ctx, listCredentialUsages, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CredentialUsage{}
	for rows.Next() {
		var i CredentialUsage
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.UsedByType,
			&i.UsedByName,
			&i.UsageContext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT c.id, c.name, c.provider, c.external_ref, c.credential_type, c.status, c.last_seen_at, c.created_at, c.updated_at,
       COALESCE(count(DISTINCT p.id), 0)::int AS permission_count,
       COALESCE(count(DISTINCT u.id), 0)::int AS usage_count
FROM credentials c
LEFT JOIN credential_permissions p ON p.credential_id = c.id
LEFT JOIN credential_usages u ON u.credential_id = c.id
GROUP BY c.id
ORDER BY c.provider, c.name
`

type ListCredentialsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Provider        string             `json:"provider"`
	ExternalRef     string             `json:"external_ref"`
	CredentialType  string             `json:"credential_type"`
	Status          string             `json:"status"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PermissionCount int32              `json:"permission_count"`
	UsageCount      int32              `json:"usage_count"`
}

func (q *Queries) ListCredentials(ctx context.Context) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.ExternalRef,
			&i.CredentialType,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PermissionCount,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentLogsAfter = `-- name: ListDeploymentLogsAfter :many
SELECT id, deployment_id, stream, message, created_at
FROM deployment_logs
WHERE deployment_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListDeploymentLogsAfterParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	LastLogID    int64       `json:"last_log_id"`
	LimitCount   int32       `json:"limit_count"`
}

func (q *Queries) ListDeploymentLogsAfter(ctx context.Context, arg ListDeploymentLogsAfterParams) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogsAfter, arg.DeploymentID, arg.LastLogID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Stream,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT d.id, d.application_id, d.server_id, d.trigger, d.strategy, d.status, d.commit_sha, d.actor, d.started_at, d.finished_at, d.created_at, d.image_ref, d.image_digest,
       a.name AS application_name,
       s.name AS server_name
FROM deployments d
JOIN applications a ON a.id = d.application_id
JOIN servers s ON s.id = d.server_id
ORDER BY d.created_at DESC
LIMIT $1
`

type ListDeploymentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	ApplicationID   pgtype.UUID        `json:"application_id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	Trigger         string             `json:"trigger"`
	Strategy        string             `json:"strategy"`
	Status          string             `json:"status"`
	CommitSha       pgtype.Text        `json:"commit_sha"`
	Actor           pgtype.Text        `json:"actor"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ImageRef        pgtype.Text        `json:"image_ref"`
	ImageDigest     pgtype.Text        `json:"image_digest"`
	ApplicationName string             `json:"application_name"`
	ServerName      string             `json:"server_name"`
}

func (q *Queries) ListDeployments(ctx context.Context, limit int32) ([]ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listDeployments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsRow{}
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ServerID,
			&i.Trigger,
			&i.Strategy,
			&i.Status,
			&i.CommitSha,
			&i.Actor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.ImageRef,
			&i.ImageDigest,
			&i.ApplicationName,
			&i.ServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT e.id, e.project_id, e.name, e.slug, e.kind, e.is_ephemeral, e.pull_request_number, e.branch, e.expires_at, e.created_at, e.updated_at,
       p.name AS project_name,
       p.slug AS project_slug
FROM environments e
JOIN projects p ON p.id = e.project_id
ORDER BY p.name, CASE e.kind WHEN 'production' THEN 1 WHEN 'development' THEN 2 ELSE 3 END, e.name
`

type ListEnvironmentsRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Kind              string             `json:"kind"`
	IsEphemeral       bool               `json:"is_ephemeral"`
	PullRequestNumber pgtype.Int4        `json:"pull_request_number"`
	Branch            pgtype.Text        `json:"branch"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProjectName       string             `json:"project_name"`
	ProjectSlug       string             `json:"project_slug"`
}

func (q *Queries) ListEnvironments(ctx context.Context) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Kind,
			&i.IsEphemeral,
			&i.PullRequestNumber,
			&i.Branch,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsForProject = `-- name: ListEnvironmentsForProject :many
SELECT id, project_id, name, slug, kind, is_ephemeral, pull_request_number, branch, expires_at, created_at, updated_at
FROM environments
WHERE project_id = $1
ORDER BY CASE kind WHEN 'production' THEN 1 WHEN 'development' THEN 2 ELSE 3 END, name
`

func (q *Queries) ListEnvironmentsForProject(ctx context.Context, projectID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Kind,
			&i.IsEphemeral,
			&i.PullRequestNumber,
			&i.Branch,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.name, p.slug, p.description, p.created_at, p.updated_at, p.default_registry_id,
       cr.name AS default_registry_name
FROM projects p
LEFT JOIN container_registries cr ON cr.id = p.default_registry_id
ORDER BY p.name
`

type ListProjectsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Description         string             `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DefaultRegistryID   pgtype.UUID        `json:"default_registry_id"`
	DefaultRegistryName pgtype.Text        `json:"default_registry_name"`
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultRegistryID,
			&i.DefaultRegistryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyRouteTargetsForApplication = `-- name: ListProxyRouteTargetsForApplication :many
SELECT pr.id,
       pr.server_id,
       pr.application_id,
       pr.domain,
       pr.upstream_url,
       pr.tls_enabled,
       pr.status,
       pr.blue_upstream_url,
       pr.green_upstream_url,
       s.name AS server_name,
       s.hostname,
       s.ssh_user,
       s.ssh_port,
       s.ssh_key_path,
       s.proxy_type
FROM proxy_routes pr
JOIN servers s ON s.id = pr.server_id
WHERE pr.application_id = $1
  AND pr.server_id = $2
ORDER BY pr.domain
`

type ListProxyRouteTargetsForApplicationParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	ServerID      pgtype.UUID `json:"server_id"`
}

type ListProxyRouteTargetsForApplicationRow struct {
	ID               pgtype.UUID `json:"id"`
	ServerID         pgtype.UUID `json:"server_id"`
	ApplicationID    pgtype.UUID `json:"application_id"`
	Domain           string      `json:"domain"`
	UpstreamUrl      string      `json:"upstream_url"`
	TlsEnabled       bool        `json:"tls_enabled"`
	Status           string      `json:"status"`
	BlueUpstreamUrl  pgtype.Text `json:"blue_upstream_url"`
	GreenUpstreamUrl pgtype.Text `json:"green_upstream_url"`
	ServerName       string      `json:"server_name"`
	Hostname         string      `json:"hostname"`
	SshUser          string      `json:"ssh_user"`
	SshPort          int32       `json:"ssh_port"`
	SshKeyPath       pgtype.Text `json:"ssh_key_path"`
	ProxyType        string      `json:"proxy_type"`
}

func (q *Queries) ListProxyRouteTargetsForApplication(ctx context.Context, arg ListProxyRouteTargetsForApplicationParams) ([]ListProxyRouteTargetsForApplicationRow, error) {
	rows, err := q.db.Query(ctx, listProxyRouteTargetsForApplication, arg.ApplicationID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxyRouteTargetsForApplicationRow{}
	for rows.Next() {
		var i ListProxyRouteTargetsForApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ApplicationID,
			&i.Domain,
			&i.UpstreamUrl,
			&i.TlsEnabled,
			&i.Status,
			&i.BlueUpstreamUrl,
			&i.GreenUpstreamUrl,
			&i.ServerName,
			&i.Hostname,
			&i.SshUser,
			&i.SshPort,
			&i.SshKeyPath,
			&i.ProxyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyRoutes = `-- name: ListProxyRoutes :many
SELECT pr.id,
       pr.server_id,
       pr.application_id,
       pr.domain,
       pr.upstream_url,
       pr.tls_enabled,
       pr.status,
       pr.last_applied_at,
       pr.created_at,
       pr.updated_at,
       pr.blue_upstream_url,
       pr.green_upstream_url,
       s.name AS server_name,
       s.proxy_type,
       a.name AS application_name
FROM proxy_routes pr
JOIN servers s ON s.id = pr.server_id
LEFT JOIN applications a ON a.id = pr.application_id
ORDER BY pr.domain
`

type ListProxyRoutesRow struct {
	ID               pgtype.UUID        `json:"id"`
	ServerID         pgtype.UUID        `json:"server_id"`
	ApplicationID    pgtype.UUID        `json:"application_id"`
	Domain           string             `json:"domain"`
	UpstreamUrl      string             `json:"upstream_url"`
	TlsEnabled       bool               `json:"tls_enabled"`
	Status           string             `json:"status"`
	LastAppliedAt    pgtype.Timestamptz `json:"last_applied_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BlueUpstreamUrl  pgtype.Text        `json:"blue_upstream_url"`
	GreenUpstreamUrl pgtype.Text        `json:"green_upstream_url"`
	ServerName       string             `json:"server_name"`
	ProxyType        string             `json:"proxy_type"`
	ApplicationName  pgtype.Text        `json:"application_name"`
}

func (q *Queries) ListProxyRoutes(ctx context.Context) ([]ListProxyRoutesRow, error) {
	rows, err := q.db.Query(ctx, listProxyRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxyRoutesRow{}
	for rows.Next() {
		var i ListProxyRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ApplicationID,
			&i.Domain,
			&i.UpstreamUrl,
			&i.TlsEnabled,
			&i.Status,
			&i.LastAppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlueUpstreamUrl,
			&i.GreenUpstreamUrl,
			&i.ServerName,
			&i.ProxyType,
			&i.ApplicationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedDeploymentsForRecovery = `-- name: ListQueuedDeploymentsForRecovery :many
SELECT id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
FROM deployments
WHERE status = 'queued'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListQueuedDeploymentsForRecovery(ctx context.Context, limit int32) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listQueuedDeploymentsForRecovery, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ServerID,
			&i.Trigger,
			&i.Strategy,
			&i.Status,
			&i.CommitSha,
			&i.Actor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.ImageRef,
			&i.ImageDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeploymentLogs = `-- name: ListRecentDeploymentLogs :many
SELECT id, deployment_id, stream, message, created_at
FROM (
    SELECT id, deployment_id, stream, message, created_at
    FROM deployment_logs
    WHERE deployment_id = $1
    ORDER BY id DESC
    LIMIT $2
) recent
ORDER BY id
`

type ListRecentDeploymentLogsParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	LimitCount   int32       `json:"limit_count"`
}

func (q *Queries) ListRecentDeploymentLogs(ctx context.Context, arg ListRecentDeploymentLogsParams) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listRecentDeploymentLogs, arg.DeploymentID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Stream,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServers = `-- name: ListServers :many
SELECT id, name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type, status, cpu_usage, memory_usage, disk_usage, last_checked_at, created_at, updated_at
FROM servers
ORDER BY name
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.SshUser,
			&i.SshPort,
			&i.SshKeyPath,
			&i.ConnectionMode,
			&i.ProxyType,
			&i.Status,
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.DiskUsage,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectorSync = `-- name: MarkConnectorSync :one
INSERT INTO connector_accounts (provider, name, enabled, config, last_sync_status, last_sync_message, last_synced_at)
VALUES ($1, $2, true, '{}', $3, $4, now())
ON CONFLICT (provider, name) DO UPDATE
SET last_sync_status = excluded.last_sync_status,
    last_sync_message = excluded.last_sync_message,
    last_synced_at = now(),
    updated_at = now()
RETURNING id, provider, name, enabled, config, last_sync_status, last_sync_message, last_synced_at, created_at, updated_at
`

type MarkConnectorSyncParams struct {
	Provider        string      `json:"provider"`
	Name            string      `json:"name"`
	LastSyncStatus  pgtype.Text `json:"last_sync_status"`
	LastSyncMessage pgtype.Text `json:"last_sync_message"`
}

func (q *Queries) MarkConnectorSync(ctx context.Context, arg MarkConnectorSyncParams) (ConnectorAccount, error) {
	row := q.db.QueryRow(ctx, markConnectorSync,
		arg.Provider,
		arg.Name,
		arg.LastSyncStatus,
		arg.LastSyncMessage,
	)
	var i ConnectorAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.LastSyncStatus,
		&i.LastSyncMessage,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProxyRouteApplied = `-- name: MarkProxyRouteApplied :one
UPDATE proxy_routes
SET status = 'applied', last_applied_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, server_id, application_id, domain, upstream_url, tls_enabled, status, last_applied_at, created_at, updated_at, blue_upstream_url, green_upstream_url
`

func (q *Queries) MarkProxyRouteApplied(ctx context.Context, id pgtype.UUID) (ProxyRoute, error) {
	row := q.db.QueryRow(ctx, markProxyRouteApplied, id)
	var i ProxyRoute
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ApplicationID,
		&i.Domain,
		&i.UpstreamUrl,
		&i.TlsEnabled,
		&i.Status,
		&i.LastAppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlueUpstreamUrl,
		&i.GreenUpstreamUrl,
	)
	return i, err
}

const markProxyRouteFailed = `-- name: MarkProxyRouteFailed :one
UPDATE proxy_routes
SET status = 'failed', updated_at = now()
WHERE id = $1
RETURNING id, server_id, application_id, domain, upstream_url, tls_enabled, status, last_applied_at, created_at, updated_at, blue_upstream_url, green_upstream_url
`

func (q *Queries) MarkProxyRouteFailed(ctx context.Context, id pgtype.UUID) (ProxyRoute, error) {
	row := q.db.QueryRow(ctx, markProxyRouteFailed, id)
	var i ProxyRoute
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ApplicationID,
		&i.Domain,
		&i.UpstreamUrl,
		&i.TlsEnabled,
		&i.Status,
		&i.LastAppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlueUpstreamUrl,
		&i.GreenUpstreamUrl,
	)
	return i, err
}

const startQueuedDeployment = `-- name: StartQueuedDeployment :one
UPDATE deployments
SET status = 'running',
    started_at = COALESCE(started_at, now())
WHERE id = $1
  AND status = 'queued'
RETURNING id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
`

func (q *Queries) StartQueuedDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, startQueuedDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Trigger,
		&i.Strategy,
		&i.Status,
		&i.CommitSha,
		&i.Actor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.ImageRef,
		&i.ImageDigest,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status = $1::text,
    current_version = CASE
        WHEN $1::text = 'healthy' THEN COALESCE($2::text, current_version)
        ELSE current_version
    END,
    target_version = CASE
        WHEN $1::text = 'deploying' THEN COALESCE($2::text, target_version)
        WHEN $1::text = 'healthy' THEN NULL
        ELSE target_version
    END,
    updated_at = now()
WHERE id = $3::uuid
RETURNING id, environment_id, server_id, name, repository_url, branch, compose_path, remote_directory, domain, health_check_url, doppler_project, doppler_config, status, current_version, target_version, created_at, updated_at, github_auto_deploy
`

type UpdateApplicationStatusParams struct {
	Status  string      `json:"status"`
	Version pgtype.Text `json:"version"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus, arg.Status, arg.Version, arg.ID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ServerID,
		&i.Name,
		&i.RepositoryUrl,
		&i.Branch,
		&i.ComposePath,
		&i.RemoteDirectory,
		&i.Domain,
		&i.HealthCheckUrl,
		&i.DopplerProject,
		&i.DopplerConfig,
		&i.Status,
		&i.CurrentVersion,
		&i.TargetVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAutoDeploy,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $2,
    started_at = COALESCE(started_at, CASE WHEN $2 = 'running' THEN now() ELSE started_at END),
    finished_at = CASE WHEN $2 IN ('succeeded', 'failed', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $1
RETURNING id, application_id, server_id, trigger, strategy, status, commit_sha, actor, started_at, finished_at, created_at, image_ref, image_digest
`

type UpdateDeploymentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Trigger,
		&i.Strategy,
		&i.Status,
		&i.CommitSha,
		&i.Actor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.ImageRef,
		&i.ImageDigest,
	)
	return i, err
}

const updateInstanceSettings = `-- name: UpdateInstanceSettings :one
UPDATE instance_settings
SET
    name = $1,
    short_name = $2,
    meta_description = $3,
    logo_url = $4,
    favicon_url = $5,
    primary_color = $6,
    docs_url = $7,
    updated_at = now()
WHERE id = (
    SELECT id
    FROM instance_settings
    ORDER BY created_at
    LIMIT 1
)
RETURNING id, name, short_name, meta_description, logo_url, favicon_url, primary_color, docs_url, created_at, updated_at
`

type UpdateInstanceSettingsParams struct {
	Name            string `json:"name"`
	ShortName       string `json:"short_name"`
	MetaDescription string `json:"meta_description"`
	LogoUrl         string `json:"logo_url"`
	FaviconUrl      string `json:"favicon_url"`
	PrimaryColor    string `json:"primary_color"`
	DocsUrl         string `json:"docs_url"`
}

func (q *Queries) UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, updateInstanceSettings,
		arg.Name,
		arg.ShortName,
		arg.MetaDescription,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.DocsUrl,
	)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.MetaDescription,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.DocsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2,
    slug = $3,
    description = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, created_at, updated_at, default_registry_id
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultRegistryID,
	)
	return i, err
}

const updateProjectRegistry = `-- name: UpdateProjectRegistry :one
UPDATE projects
SET default_registry_id = $1::uuid,
    updated_at = now()
WHERE id = $2::uuid
RETURNING id, name, slug, description, created_at, updated_at, default_registry_id
`

type UpdateProjectRegistryParams struct {
	DefaultRegistryID pgtype.UUID `json:"default_registry_id"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProjectRegistry(ctx context.Context, arg UpdateProjectRegistryParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectRegistry, arg.DefaultRegistryID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultRegistryID,
	)
	return i, err
}

const updateProxyRouteUpstream = `-- name: UpdateProxyRouteUpstream :one
UPDATE proxy_routes
SET upstream_url = $2,
    status = 'pending',
    updated_at = now()
WHERE id = $1
RETURNING id, server_id, application_id, domain, upstream_url, tls_enabled, status, last_applied_at, created_at, updated_at, blue_upstream_url, green_upstream_url
`

type UpdateProxyRouteUpstreamParams struct {
	ID          pgtype.UUID `json:"id"`
	UpstreamUrl string      `json:"upstream_url"`
}

func (q *Queries) UpdateProxyRouteUpstream(ctx context.Context, arg UpdateProxyRouteUpstreamParams) (ProxyRoute, error) {
	row := q.db.QueryRow(ctx, updateProxyRouteUpstream, arg.ID, arg.UpstreamUrl)
	var i ProxyRoute
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.ApplicationID,
		&i.Domain,
		&i.UpstreamUrl,
		&i.TlsEnabled,
		&i.Status,
		&i.LastAppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlueUpstreamUrl,
		&i.GreenUpstreamUrl,
	)
	return i, err
}

const updateServerHealth = `-- name: UpdateServerHealth :one
UPDATE servers
SET status = $2, cpu_usage = $3, memory_usage = $4, disk_usage = $5, last_checked_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, name, hostname, ssh_user, ssh_port, ssh_key_path, connection_mode, proxy_type, status, cpu_usage, memory_usage, disk_usage, last_checked_at, created_at, updated_at
`

type UpdateServerHealthParams struct {
	ID          pgtype.UUID    `json:"id"`
	Status      string         `json:"status"`
	CpuUsage    pgtype.Numeric `json:"cpu_usage"`
	MemoryUsage pgtype.Numeric `json:"memory_usage"`
	DiskUsage   pgtype.Numeric `json:"disk_usage"`
}

func (q *Queries) UpdateServerHealth(ctx context.Context, arg UpdateServerHealthParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerHealth,
		arg.ID,
		arg.Status,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.DiskUsage,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.SshUser,
		&i.SshPort,
		&i.SshKeyPath,
		&i.ConnectionMode,
		&i.ProxyType,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.DiskUsage,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnectorAccount = `-- name: UpsertConnectorAccount :one
INSERT INTO connector_accounts (provider, name, enabled, config)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider, name) DO UPDATE
SET enabled = excluded.enabled,
    config = excluded.config,
    last_sync_status = CASE
        WHEN connector_accounts.enabled IS DISTINCT FROM excluded.enabled OR connector_accounts.config IS DISTINCT FROM excluded.config THEN NULL
        ELSE connector_accounts.last_sync_status
    END,
    last_sync_message = CASE
        WHEN connector_accounts.enabled IS DISTINCT FROM excluded.enabled OR connector_accounts.config IS DISTINCT FROM excluded.config THEN NULL
        ELSE connector_accounts.last_sync_message
    END,
    last_synced_at = CASE
        WHEN connector_accounts.enabled IS DISTINCT FROM excluded.enabled OR connector_accounts.config IS DISTINCT FROM excluded.config THEN NULL
        ELSE connector_accounts.last_synced_at
    END,
    updated_at = now()
RETURNING id, provider, name, enabled, config, last_sync_status, last_sync_message, last_synced_at, created_at, updated_at
`

type UpsertConnectorAccountParams struct {
	Provider string `json:"provider"`
	Name     string `json:"name"`
	Enabled  bool   `json:"enabled"`
	Config   []byte `json:"config"`
}

func (q *Queries) UpsertConnectorAccount(ctx context.Context, arg UpsertConnectorAccountParams) (ConnectorAccount, error) {
	row := q.db.QueryRow(ctx, upsertConnectorAccount,
		arg.Provider,
		arg.Name,
		arg.Enabled,
		arg.Config,
	)
	var i ConnectorAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.LastSyncStatus,
		&i.LastSyncMessage,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContainerRegistry = `-- name: UpsertContainerRegistry :one
INSERT INTO container_registries (name, provider, registry_host, namespace, repository, default_image, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (name) DO UPDATE
SET provider = excluded.provider,
    registry_host = excluded.registry_host,
    namespace = excluded.namespace,
    repository = excluded.repository,
    default_image = excluded.default_image,
    enabled = excluded.enabled,
    updated_at = now()
RETURNING id, name, provider, registry_host, namespace, repository, default_image, enabled, created_at, updated_at
`

type UpsertContainerRegistryParams struct {
	Name         string `json:"name"`
	Provider     string `json:"provider"`
	RegistryHost string `json:"registry_host"`
	Namespace    string `json:"namespace"`
	Repository   string `json:"repository"`
	DefaultImage string `json:"default_image"`
	Enabled      bool   `json:"enabled"`
}

func (q *Queries) UpsertContainerRegistry(ctx context.Context, arg UpsertContainerRegistryParams) (ContainerRegistry, error) {
	row := q.db.QueryRow(ctx, upsertContainerRegistry,
		arg.Name,
		arg.Provider,
		arg.RegistryHost,
		arg.Namespace,
		arg.Repository,
		arg.DefaultImage,
		arg.Enabled,
	)
	var i ContainerRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.RegistryHost,
		&i.Namespace,
		&i.Repository,
		&i.DefaultImage,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCredential = `-- name: UpsertCredential :one
INSERT INTO credentials (name, provider, external_ref, credential_type, status, last_seen_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (provider, external_ref) DO UPDATE
SET name = excluded.name,
    credential_type = excluded.credential_type,
    status = excluded.status,
    last_seen_at = now(),
    updated_at = now()
RETURNING id, name, provider, external_ref, credential_type, status, last_seen_at, created_at, updated_at
`

type UpsertCredentialParams struct {
	Name           string `json:"name"`
	Provider       string `json:"provider"`
	ExternalRef    string `json:"external_ref"`
	CredentialType string `json:"credential_type"`
	Status         string `json:"status"`
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, upsertCredential,
		arg.Name,
		arg.Provider,
		arg.ExternalRef,
		arg.CredentialType,
		arg.Status,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.ExternalRef,
		&i.CredentialType,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCredentialPermission = `-- name: UpsertCredentialPermission :one
INSERT INTO credential_permissions (credential_id, resource_type, resource_name, permission, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (credential_id, resource_type, resource_name, permission) DO UPDATE
SET source = excluded.source
RETURNING id, credential_id, resource_type, resource_name, permission, source, created_at
`

type UpsertCredentialPermissionParams struct {
	CredentialID pgtype.UUID `json:"credential_id"`
	ResourceType string      `json:"resource_type"`
	ResourceName string      `json:"resource_name"`
	Permission   string      `json:"permission"`
	Source       string      `json:"source"`
}

func (q *Queries) UpsertCredentialPermission(ctx context.Context, arg UpsertCredentialPermissionParams) (CredentialPermission, error) {
	row := q.db.QueryRow(ctx, upsertCredentialPermission,
		arg.CredentialID,
		arg.ResourceType,
		arg.ResourceName,
		arg.Permission,
		arg.Source,
	)
	var i CredentialPermission
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.ResourceType,
		&i.ResourceName,
		&i.Permission,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCredentialUsage = `-- name: UpsertCredentialUsage :one
INSERT INTO credential_usages (credential_id, used_by_type, used_by_name, usage_context)
VALUES ($1, $2, $3, $4)
ON CONFLICT (credential_id, used_by_type, used_by_name, usage_context) DO UPDATE
SET usage_context = excluded.usage_context
RETURNING id, credential_id, used_by_type, used_by_name, usage_context, created_at
`

type UpsertCredentialUsageParams struct {
	CredentialID pgtype.UUID `json:"credential_id"`
	UsedByType   string      `json:"used_by_type"`
	UsedByName   string      `json:"used_by_name"`
	UsageContext string      `json:"usage_context"`
}

func (q *Queries) UpsertCredentialUsage(ctx context.Context, arg UpsertCredentialUsageParams) (CredentialUsage, error) {
	row := q.db.QueryRow(ctx, upsertCredentialUsage,
		arg.CredentialID,
		arg.UsedByType,
		arg.UsedByName,
		arg.UsageContext,
	)
	var i CredentialUsage
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.UsedByType,
		&i.UsedByName,
		&i.UsageContext,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDeploymentSlot = `-- name: UpsertDeploymentSlot :one
INSERT INTO application_deployment_slots (application_id, server_id, color, deployment_id, image_ref, image_digest, status, promoted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, CASE WHEN $7 = 'active' THEN now() ELSE NULL END)
ON CONFLICT (application_id, server_id, color) DO UPDATE
SET deployment_id = excluded.deployment_id,
    image_ref = excluded.image_ref,
    image_digest = excluded.image_digest,
    status = excluded.status,
    promoted_at = excluded.promoted_at,
    updated_at = now()
RETURNING id, application_id, server_id, color, deployment_id, image_ref, image_digest, status, promoted_at, created_at, updated_at
`

type UpsertDeploymentSlotParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	ServerID      pgtype.UUID `json:"server_id"`
	Color         string      `json:"color"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
	ImageRef      string      `json:"image_ref"`
	ImageDigest   pgtype.Text `json:"image_digest"`
	Status        string      `json:"status"`
}

func (q *Queries) UpsertDeploymentSlot(ctx context.Context, arg UpsertDeploymentSlotParams) (ApplicationDeploymentSlot, error) {
	row := q.db.QueryRow(ctx, upsertDeploymentSlot,
		arg.ApplicationID,
		arg.ServerID,
		arg.Color,
		arg.DeploymentID,
		arg.ImageRef,
		arg.ImageDigest,
		arg.Status,
	)
	var i ApplicationDeploymentSlot
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ServerID,
		&i.Color,
		&i.DeploymentID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.Status,
		&i.PromotedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
