// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID               pgtype.UUID        `json:"id"`
	EnvironmentID    pgtype.UUID        `json:"environment_id"`
	ServerID         pgtype.UUID        `json:"server_id"`
	Name             string             `json:"name"`
	RepositoryUrl    pgtype.Text        `json:"repository_url"`
	Branch           string             `json:"branch"`
	ComposePath      string             `json:"compose_path"`
	RemoteDirectory  string             `json:"remote_directory"`
	Domain           pgtype.Text        `json:"domain"`
	HealthCheckUrl   pgtype.Text        `json:"health_check_url"`
	DopplerProject   pgtype.Text        `json:"doppler_project"`
	DopplerConfig    pgtype.Text        `json:"doppler_config"`
	Status           string             `json:"status"`
	CurrentVersion   pgtype.Text        `json:"current_version"`
	TargetVersion    pgtype.Text        `json:"target_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	GithubAutoDeploy bool               `json:"github_auto_deploy"`
}

type ApplicationDeploymentSlot struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	ServerID      pgtype.UUID        `json:"server_id"`
	Color         string             `json:"color"`
	DeploymentID  pgtype.UUID        `json:"deployment_id"`
	ImageRef      string             `json:"image_ref"`
	ImageDigest   pgtype.Text        `json:"image_digest"`
	Status        string             `json:"status"`
	PromotedAt    pgtype.Timestamptz `json:"promoted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID         int64              `json:"id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	TargetName string             `json:"target_name"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ConnectorAccount struct {
	ID              pgtype.UUID        `json:"id"`
	Provider        string             `json:"provider"`
	Name            string             `json:"name"`
	Enabled         bool               `json:"enabled"`
	Config          []byte             `json:"config"`
	LastSyncStatus  pgtype.Text        `json:"last_sync_status"`
	LastSyncMessage pgtype.Text        `json:"last_sync_message"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ContainerRegistry struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Provider     string             `json:"provider"`
	RegistryHost string             `json:"registry_host"`
	Namespace    string             `json:"namespace"`
	Repository   string             `json:"repository"`
	DefaultImage string             `json:"default_image"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Credential struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Provider       string             `json:"provider"`
	ExternalRef    string             `json:"external_ref"`
	CredentialType string             `json:"credential_type"`
	Status         string             `json:"status"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CredentialPermission struct {
	ID           pgtype.UUID        `json:"id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
	ResourceType string             `json:"resource_type"`
	ResourceName string             `json:"resource_name"`
	Permission   string             `json:"permission"`
	Source       string             `json:"source"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CredentialUsage struct {
	ID           pgtype.UUID        `json:"id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
	UsedByType   string             `json:"used_by_type"`
	UsedByName   string             `json:"used_by_name"`
	UsageContext string             `json:"usage_context"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Deployment struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	ServerID      pgtype.UUID        `json:"server_id"`
	Trigger       string             `json:"trigger"`
	Strategy      string             `json:"strategy"`
	Status        string             `json:"status"`
	CommitSha     pgtype.Text        `json:"commit_sha"`
	Actor         pgtype.Text        `json:"actor"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ImageRef      pgtype.Text        `json:"image_ref"`
	ImageDigest   pgtype.Text        `json:"image_digest"`
}

type DeploymentLog struct {
	ID           int64              `json:"id"`
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	Stream       string             `json:"stream"`
	Message      string             `json:"message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Environment struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Kind              string             `json:"kind"`
	IsEphemeral       bool               `json:"is_ephemeral"`
	PullRequestNumber pgtype.Int4        `json:"pull_request_number"`
	Branch            pgtype.Text        `json:"branch"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type InstanceSetting struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	ShortName       string             `json:"short_name"`
	MetaDescription string             `json:"meta_description"`
	LogoUrl         string             `json:"logo_url"`
	FaviconUrl      string             `json:"favicon_url"`
	PrimaryColor    string             `json:"primary_color"`
	DocsUrl         string             `json:"docs_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DefaultRegistryID pgtype.UUID        `json:"default_registry_id"`
}

type ProxyRoute struct {
	ID               pgtype.UUID        `json:"id"`
	ServerID         pgtype.UUID        `json:"server_id"`
	ApplicationID    pgtype.UUID        `json:"application_id"`
	Domain           string             `json:"domain"`
	UpstreamUrl      string             `json:"upstream_url"`
	TlsEnabled       bool               `json:"tls_enabled"`
	Status           string             `json:"status"`
	LastAppliedAt    pgtype.Timestamptz `json:"last_applied_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BlueUpstreamUrl  pgtype.Text        `json:"blue_upstream_url"`
	GreenUpstreamUrl pgtype.Text        `json:"green_upstream_url"`
}

type Server struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Hostname      string             `json:"hostname"`
	SshUser       string             `json:"ssh_user"`
	SshPort       int32              `json:"ssh_port"`
	SshKeyPath    pgtype.Text        `json:"ssh_key_path"`
	ProxyType     string             `json:"proxy_type"`
	Status        string             `json:"status"`
	CpuUsage      pgtype.Numeric     `json:"cpu_usage"`
	MemoryUsage   pgtype.Numeric     `json:"memory_usage"`
	DiskUsage     pgtype.Numeric     `json:"disk_usage"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
