// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error)
	AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) (DeploymentLog, error)
	CancelQueuedDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateProjectWithDefaultEnvironments(ctx context.Context, arg CreateProjectWithDefaultEnvironmentsParams) (CreateProjectWithDefaultEnvironmentsRow, error)
	CreateProxyRoute(ctx context.Context, arg CreateProxyRouteParams) (ProxyRoute, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateServerWithSSHInventory(ctx context.Context, arg CreateServerWithSSHInventoryParams) (CreateServerWithSSHInventoryRow, error)
	DeleteCredentialPermissions(ctx context.Context, credentialID pgtype.UUID) error
	DeleteCredentialUsages(ctx context.Context, credentialID pgtype.UUID) error
	FailRunningDeploymentsForRecovery(ctx context.Context) ([]FailRunningDeploymentsForRecoveryRow, error)
	GetApplication(ctx context.Context, id pgtype.UUID) (Application, error)
	GetConnectorAccount(ctx context.Context, id pgtype.UUID) (ConnectorAccount, error)
	GetCredential(ctx context.Context, id pgtype.UUID) (Credential, error)
	GetCredentialWithCounts(ctx context.Context, id pgtype.UUID) (GetCredentialWithCountsRow, error)
	GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	GetDeploymentTarget(ctx context.Context, id pgtype.UUID) (GetDeploymentTargetRow, error)
	GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error)
	GetInstanceSettings(ctx context.Context) (InstanceSetting, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProxyRouteTarget(ctx context.Context, id pgtype.UUID) (GetProxyRouteTargetRow, error)
	GetServer(ctx context.Context, id pgtype.UUID) (Server, error)
	ListApplications(ctx context.Context) ([]ListApplicationsRow, error)
	ListApplicationsForGitHubPush(ctx context.Context, arg ListApplicationsForGitHubPushParams) ([]ListApplicationsForGitHubPushRow, error)
	ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error)
	ListConnectorAccounts(ctx context.Context) ([]ConnectorAccount, error)
	ListCredentialPermissions(ctx context.Context, credentialID pgtype.UUID) ([]CredentialPermission, error)
	ListCredentialUsages(ctx context.Context, credentialID pgtype.UUID) ([]CredentialUsage, error)
	ListCredentials(ctx context.Context) ([]ListCredentialsRow, error)
	ListDeploymentLogsAfter(ctx context.Context, arg ListDeploymentLogsAfterParams) ([]DeploymentLog, error)
	ListDeployments(ctx context.Context, limit int32) ([]ListDeploymentsRow, error)
	ListEnvironments(ctx context.Context) ([]ListEnvironmentsRow, error)
	ListEnvironmentsForProject(ctx context.Context, projectID pgtype.UUID) ([]Environment, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProxyRouteTargetsForApplication(ctx context.Context, arg ListProxyRouteTargetsForApplicationParams) ([]ListProxyRouteTargetsForApplicationRow, error)
	ListProxyRoutes(ctx context.Context) ([]ListProxyRoutesRow, error)
	ListQueuedDeploymentsForRecovery(ctx context.Context, limit int32) ([]Deployment, error)
	ListRecentDeploymentLogs(ctx context.Context, arg ListRecentDeploymentLogsParams) ([]DeploymentLog, error)
	ListServers(ctx context.Context) ([]Server, error)
	MarkConnectorSync(ctx context.Context, arg MarkConnectorSyncParams) (ConnectorAccount, error)
	MarkProxyRouteApplied(ctx context.Context, id pgtype.UUID) (ProxyRoute, error)
	MarkProxyRouteFailed(ctx context.Context, id pgtype.UUID) (ProxyRoute, error)
	StartQueuedDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error)
	UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (InstanceSetting, error)
	UpdateServerHealth(ctx context.Context, arg UpdateServerHealthParams) (Server, error)
	UpsertConnectorAccount(ctx context.Context, arg UpsertConnectorAccountParams) (ConnectorAccount, error)
	UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (Credential, error)
	UpsertCredentialPermission(ctx context.Context, arg UpsertCredentialPermissionParams) (CredentialPermission, error)
	UpsertCredentialUsage(ctx context.Context, arg UpsertCredentialUsageParams) (CredentialUsage, error)
}

var _ Querier = (*Queries)(nil)
