// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateDeploymentSlot(ctx context.Context, arg ActivateDeploymentSlotParams) ([]ApplicationDeploymentSlot, error)
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error)
	AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) (DeploymentLog, error)
	CancelQueuedDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	CompleteBuildRun(ctx context.Context, arg CompleteBuildRunParams) (BuildRun, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateBuildRun(ctx context.Context, arg CreateBuildRunParams) (BuildRun, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateProjectWithDefaultEnvironments(ctx context.Context, arg CreateProjectWithDefaultEnvironmentsParams) (CreateProjectWithDefaultEnvironmentsRow, error)
	CreateProxyRoute(ctx context.Context, arg CreateProxyRouteParams) (ProxyRoute, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateServerWithSSHInventory(ctx context.Context, arg CreateServerWithSSHInventoryParams) (CreateServerWithSSHInventoryRow, error)
	DeleteApplication(ctx context.Context, id pgtype.UUID) error
	DeleteCredentialPermissions(ctx context.Context, credentialID pgtype.UUID) error
	DeleteCredentialUsages(ctx context.Context, credentialID pgtype.UUID) error
	DeleteEnvironment(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteProxyRoute(ctx context.Context, id pgtype.UUID) error
	DeleteServerDevSudoUser(ctx context.Context, arg DeleteServerDevSudoUserParams) error
	FailRunningDeploymentsForRecovery(ctx context.Context) ([]FailRunningDeploymentsForRecoveryRow, error)
	GetActiveDeploymentSlot(ctx context.Context, arg GetActiveDeploymentSlotParams) (ApplicationDeploymentSlot, error)
	GetApplication(ctx context.Context, id pgtype.UUID) (Application, error)
	GetBuildRun(ctx context.Context, id pgtype.UUID) (BuildRun, error)
	GetConnectorAccount(ctx context.Context, id pgtype.UUID) (ConnectorAccount, error)
	GetContainerRegistry(ctx context.Context, id pgtype.UUID) (ContainerRegistry, error)
	GetCredential(ctx context.Context, id pgtype.UUID) (Credential, error)
	GetCredentialWithCounts(ctx context.Context, id pgtype.UUID) (GetCredentialWithCountsRow, error)
	GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	GetDeploymentTarget(ctx context.Context, id pgtype.UUID) (GetDeploymentTargetRow, error)
	GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error)
	GetInstanceSettings(ctx context.Context) (InstanceSetting, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProxyRouteTarget(ctx context.Context, id pgtype.UUID) (GetProxyRouteTargetRow, error)
	GetServer(ctx context.Context, id pgtype.UUID) (Server, error)
	GetStandbyDeploymentSlot(ctx context.Context, arg GetStandbyDeploymentSlotParams) (ApplicationDeploymentSlot, error)
	ListApplications(ctx context.Context) ([]ListApplicationsRow, error)
	ListApplicationsForBuildComplete(ctx context.Context, arg ListApplicationsForBuildCompleteParams) ([]ListApplicationsForBuildCompleteRow, error)
	ListApplicationsForGitHubPush(ctx context.Context, arg ListApplicationsForGitHubPushParams) ([]ListApplicationsForGitHubPushRow, error)
	ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error)
	ListBuildRuns(ctx context.Context, limit int32) ([]BuildRun, error)
	ListConnectorAccounts(ctx context.Context) ([]ConnectorAccount, error)
	ListContainerRegistries(ctx context.Context) ([]ContainerRegistry, error)
	ListCredentialPermissions(ctx context.Context, credentialID pgtype.UUID) ([]CredentialPermission, error)
	ListCredentialUsages(ctx context.Context, credentialID pgtype.UUID) ([]CredentialUsage, error)
	ListCredentials(ctx context.Context) ([]ListCredentialsRow, error)
	ListDeploymentLogsAfter(ctx context.Context, arg ListDeploymentLogsAfterParams) ([]DeploymentLog, error)
	ListDeployments(ctx context.Context, limit int32) ([]ListDeploymentsRow, error)
	ListEnvironments(ctx context.Context) ([]ListEnvironmentsRow, error)
	ListEnvironmentsForProject(ctx context.Context, projectID pgtype.UUID) ([]Environment, error)
	ListProjects(ctx context.Context) ([]ListProjectsRow, error)
	ListProxyRouteTargetsForApplication(ctx context.Context, arg ListProxyRouteTargetsForApplicationParams) ([]ListProxyRouteTargetsForApplicationRow, error)
	ListProxyRoutes(ctx context.Context) ([]ListProxyRoutesRow, error)
	ListQueuedDeploymentsForRecovery(ctx context.Context, limit int32) ([]Deployment, error)
	ListRecentDeploymentLogs(ctx context.Context, arg ListRecentDeploymentLogsParams) ([]DeploymentLog, error)
	ListServerDevSudoUsers(ctx context.Context, serverID pgtype.UUID) ([]ServerDevSudoUser, error)
	ListServers(ctx context.Context) ([]Server, error)
	MarkConnectorSync(ctx context.Context, arg MarkConnectorSyncParams) (ConnectorAccount, error)
	MarkProxyRouteApplied(ctx context.Context, id pgtype.UUID) (ProxyRoute, error)
	MarkProxyRouteFailed(ctx context.Context, id pgtype.UUID) (ProxyRoute, error)
	RenameServerDevSudoUser(ctx context.Context, arg RenameServerDevSudoUserParams) (ServerDevSudoUser, error)
	ReplaceServerDevSudoUsers(ctx context.Context, arg ReplaceServerDevSudoUsersParams) error
	StartQueuedDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error)
	UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (InstanceSetting, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectRegistry(ctx context.Context, arg UpdateProjectRegistryParams) (Project, error)
	UpdateProxyRouteUpstream(ctx context.Context, arg UpdateProxyRouteUpstreamParams) (ProxyRoute, error)
	UpdateServerHealth(ctx context.Context, arg UpdateServerHealthParams) (Server, error)
	UpsertConnectorAccount(ctx context.Context, arg UpsertConnectorAccountParams) (ConnectorAccount, error)
	UpsertContainerRegistry(ctx context.Context, arg UpsertContainerRegistryParams) (ContainerRegistry, error)
	UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (Credential, error)
	UpsertCredentialPermission(ctx context.Context, arg UpsertCredentialPermissionParams) (CredentialPermission, error)
	UpsertCredentialUsage(ctx context.Context, arg UpsertCredentialUsageParams) (CredentialUsage, error)
	UpsertDeploymentSlot(ctx context.Context, arg UpsertDeploymentSlotParams) (ApplicationDeploymentSlot, error)
	UpsertServerDevSudoUser(ctx context.Context, arg UpsertServerDevSudoUserParams) (ServerDevSudoUser, error)
}

var _ Querier = (*Queries)(nil)
